### PR TITLE
Using ui-avatars to generate avatar if logged in player doesn't have …

### PR DESCRIPTION
**Pull request by rythos42**
…one set

This attempts to fix issue #33 by auto-generating an avatar if one isn't present from the user profile.

### CODE REVIEW

**Comment by videege** [comment]
I like this - I wasn't aware of this service.  Thanks!

**Comment by rythos42** [comment]
I knew something like this had to exist, I assumed it would be a library but this is pretty good!

When do you do releases? I was going to think more about my other logged Issues, but wanted to see where this simple one went to before I did anything with them. :)

**Comment by videege** [comment]
Right now I'm using GitHub actions to deploy to Firebase - I merged your changes to the release branch so they should be deployed in just a couple minutes.

**Comment by rythos42** [comment]
That's awesome, I'm stoked!

**Pull request merged**
