### PR TITLE
Make tabs on Campaign be sub-navigation under /campaigns/{campaignId}

### LINKED ISSUE #11: mat-list-avatar icon on campaign page has null src
mat-list-avatar icon on campaign page has null src and shows a broken image.

### LINKED ISSUE #32: Going back from Roster->Fleet should go back to Roster
When in a Campaign, on the Roster tab, click "..." next to a fleet and click "View / Edit Fleet". This takes you to the fleet view.

In Chrome (and likely other places), the usual ways out at not intuitive.

1. Clicking one level up on the top breadcrumb takes you to fleets (which is, by the way, a list of _your fleets_ and does not necessarily contain the fleet you were just looking at).
2. Clicking back on the browser takes you to the Campaign page, but onto the Manager tab rather than Roster tab.

Both of these things aren't intuitive:

1. The breadcrumb should be "Campaign > {Current Fleet}"
2. "Back" should take you to the Roster tab on the Campaign page.

### LINKED ISSUE #37: Played campaign objectives not shown anywhere
It appears as though they are stored in `CampaignLocation.playedCampaignObjectives`, and used to show a little tag on the campaign pool selection, but that they aren't shown outside of the battle phase.

It would be helpful for planning future phases if this information was shown in the general UI. 

1. In Locations, for general planning.
2. In Timeline, for looking back at what happened.

### LINKED ISSUE #38: Low Fuel given when adjacent sector has friendly base and border location is controller by friendly.
**Steps to reproduce**
- Rebels have a base on Kessel (sector 3)
- Rebels have presence on Lothal (sector 2/3)
- Rebels assault Mon Cala (sector 3)

_Expected:_ That the Rebel fleet does not gain Low Fuel.
_Actual:_ The Rebel fleet gains Low Fuel.

### LINKED ISSUE #41: Bases only able to be built on presence from last round, rather than new presence.
On page 17 of the rulebook, *Determine Battle Effects*, the order is that you update the map based on results from the battles and then can construct new bases. This means that you may build a base on locations that were _just assigned presence_. The UI currently restricts you to places that had presence _last round._

### LINKED ISSUE #44: Token for newly created based not showing in list
In the Management Phase, you build bases and then collect tokens for bases and presence gained that turn. Currently the system doesn't appear to give you a token when you build a new base (the new selected base doesn't appear in the list of tokens under it).

image

In this picture, I would have expected "Nal Hutta" to appear as an option where the lower yellow line is.

### PR DESCRIPTION
**Pull request by rythos42**
My goal was to fix #32 . I realized while looking into this, that my logged issue consisted of two problems:

1. That I wanted `/fleets/{fleetId}` that were actually campaign fleets, to exist under `/campaigns/{campaignId}/fleets/{fleetId}` because these are _campaign fleets_. This would enable the breadcrumb to work properly.
2. That I wanted pressing "back" in the browser to go back to the Roster tab on `/campaigns/{campaignId}`.

In looking into how to achieve 1, I realized I needed **much** more knowledge about Angular and components before this was going to be possible. :P I'm a React/JS developer, and haven't touched Angular since 1.0 and don't use TS, so this got hairy quick. In researching this, I created my own Firebase account and got that working, so I created some documentation to help others get to where I got to (commit 32b8036). And since a fix for 2 was possible and enough, I decided to leave this issue for another day (or never...).

2 I solved by creating routes under `/campaigns/{campaignId}` with the names of `managers`, `roster`, `locations`, and `timeline`, which allows that if you navigate from Roster to a fleet and press back, that you go back to `/campaigns/{campaignId}/roster`. Which is good enough for me. :) (commit 270a212)

------------------
Notes on the fix...

I haven't used Angular since 1.0, and React is really different, so a lot of this stuff is pretty foreign to me. I would have loved to do differently:

1. `getSubNavIndex`, I don't love that this is hardcoding names and translating them into indexes. I'd prefer if this could read the known available tabs from the html/template and use a property on each `mat-tab` to determine which tab is the correct one. I wasn't certain how to do this, and this method seemed good enough given that there won't likely be a lot more tabs in this area. Maybe you have other ideas?

2. In `campaign-routing.module.ts` I copy/paste the same route 4 times, just with slightly different `path` and different `subNav` value. Is there a better way to write this that I don't know about? This is a lot of copied code that is identical. :(

Thanks!

--------------------

So many things!

Trying to make the Issue list link to this PR.

Fixes #37 
Fixes #44 
Fixes #41 
Fixes #38 
Fixes #11

### CODE REVIEW

**Comment by rythos42** [comment]
68c277b and ccacbcb were added because in playing around I found that the routes weren't quite right.

359a0f4 and 9c365b3 attempt to fix the issue #37 where played campaign objectives were hard to find when not directly in the battle phase, which made planning ahead more difficult. 359a0f4 adds the text "[Already Played]" to the locations objective field, and 9c365b3 adds the name of the played objective to the timeline view (regardless of whether it was a campaign objective or not).

**Comment by rythos42** [comment]
e9e620a fixes #37 which gives a fleet Low Fuel even if there is a friendly base in an adjacent area and the border is controlled by friendlies. I'm not sure why this wasn't just throwing, since `friendlyBorderLocation.sectors.find()` returns a number or undefined, neither of which can be indexed like an array. This should fix it.

**Comment by videege** [comment]
Thank you for this!  I'm on extended hours at work so I will review as soon as possible.  I really appreciate the contribution.

**Comment by rythos42** [comment]
No problem! It's been a fun project after the kid goes to bed. :P 

I've got some more bugs we've found that I'd like to fix, but I don't want to overwhelm you on this PR (but I also want to fix bugs :P). Any thoughts? I'm contemplating figuring out how to set up Firebase for my own copy of this to run with my campaign group, if you're still really busy!

(and I really understand extended hours...my day job is a niche sector of financial technology that can really help during COVID so my team and I have been working at a breakneck pace these last few weeks :P)

**Comment by rythos42** [comment]
Added a fix for #44 which I logged a couple days ago. This one was fairly simple, just looping over the combined array of tokenLocations and newBases.

**Comment by rythos42** [comment]
Added a fix for #41, which I also logged a couple days ago. When you put presence on a location, you should be able to create a base on it right away if you're eligible to create bases at all.

**Comment by videege** [comment]
Thank you so much for all these fixes.  I'm going to merge them in and then I'll see if I can improve the navigation redundancy in the future.

**Comment by rythos42** [comment]
No problem at all! 

To be honest, Flagship is the kind of thing I usually build myself because I have an itch. The fact that you've built it already, and I just need to tweak it, is pretty awesome. I'm loving contributing!

**Pull request merged**
